FileNotFoundError in line 152 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_02.py:
File b'/home/PERSONALE/eugenio.fonzi2//home/PERSONALE/eugenio.fonzi2/TEST/171228_how_many_patients_per_loop/dataset.tsv' does not exist
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_02.py", line 152, in <module>
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1695, in __init__
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
