Error in rule fastq_checkpoint:
    jobid: 0
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/171222_test_20_bwa_threads/01_fastq/02_postprocess/239_R1.fastq, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/171222_test_20_bwa_threads/01_fastq/02_postprocess/239_R2.fastq

RuleException:
NameError in line 416 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_01.py:
name 'ErrorValue' is not defined
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_01.py", line 416, in __rule_fastq_checkpoint
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
