Error in rule fastq_checkpoint:
    jobid: 0
    output: /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180103_test_adapters_YES_on_contaminated/01_fastq/02_postprocess/B2044S_R1.fastq, /home/PERSONALE/eugenio.fonzi2/ANALYSES_WES/180103_test_adapters_YES_on_contaminated/01_fastq/02_postprocess/B2044S_R2.fastq

RuleException:
NameError in line 428 of /home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_03.py:
name 'ErrorValue' is not defined
  File "/home/PERSONALE/eugenio.fonzi2/WESPipeline/snakefile_03.py", line 428, in __rule_fastq_checkpoint
  File "/home/PERSONALE/eugenio.fonzi2/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
